### ISSUE TITLE
Rellease please

### ISSUE THREAD

**Issue by PitaLife** [WilliamDo/family-fortunes#1]
I've tried this project of yours "family fortunes java".  But, can you release your first project this one "family fortunes java" ????

**Comment by WilliamDo** [comment]
Hi @PitaLife, thank you for trying it out. May I ask which platform you intend to run this on? I can easily provide a macOS version but will need some time to prepare it for Windows or Linux.

**Comment by PitaLife** [comment]
But, you don't have the released version yet

**Comment by WilliamDo** [comment]
Created new release: https://github.com/WilliamDo/family-fortunes/releases/tag/v0.1-alpha

**Comment by PitaLife** [comment]
okay, i'm try on that. but how do you edit the questions and answers in the game
